### ISSUE TITLE
hide vcal export in event detail

### ISSUE THREAD

**Issue by ermancio** [arshaw/ghi-scoreboard#2]
Hi.
I would like to hide the iCal export function for my Solgema Full calendar in Plone 4.
I did it for the Plone collection (display: none in solgemafullcalendar.css) but I'm not able to hide them (initial and end date) in the event detail (within the event popup clicking on the event itself).
Any suggestion?

Thank you
Luca

**Comment by arshaw** [comment]
u must have posted on the wrong issue tracker. fullcalendar's tracker: https://github.com/fullcalendar/fullcalendar/issues
